### ISSUE TITLE
Operator Mono italic on Windows VS 2019?

### ISSUE THREAD

**Issue by Nothing-Works** [mhoumann/CommentsPlus#11]
Anyone using Operator Mono on Windows VS 2019?

I'm having trouble with the italic font.

Any help is appreciated.

Thanks

**Comment by mhoumann** [comment]
I don't own a copy of the Operator Mono font. So I can't test it.
But I've had the question before.
If I recall, selecting a different font weight, e.g., Regular instead of Medium may work.
The typeface needs to have some settings from the creator that link different weights of the 'normal' non cursive to corresponding italics versions.  Otherwise the WPF default mechanism for italics doesn't work.

**Comment by Nothing-Works** [comment]
oh, I see, thank you for your reply.
