### ISSUE TITLE
Doesn't seem to work in VS2013

### ISSUE THREAD

**Issue by ghost** [mhoumann/CommentsPlus#3]
I downloaded the files, loaded CommentsPlus-v11.sln and then compiled in VS2015 Community and built the vsix (I wanted to remove the italics). This vsix installs and works fine in VS2015. However my daily box runs VS2013 and it doesn't work in there. It installs fine, but the additional Comments items don't show up in Fonts & Colors settings, and nothing happens. 

Any idea what might be wrong?

**Comment by mhoumann** [comment]
There are a couple of issues I've run into:
I just updated the solution to support VS 2017 RC which was quite a pain. If that is the source version you used, it actually needs to be built with 2017. Otherwise be sure to get an earlier version of the source.

If you do get the earlier version you need to build it with VS2013 and the 2013 VS SDK. Otherwise it won't work on 2013.

BUT if you just want to disable italics, you could just download the latest published VSIX and change settings in the registry:
HKCU\Software\CommentsPlus
 - DWORD value EnableTags
 - DWORD value EnableItalics
